
// This file has been generated by the GUI designer. Do not modify.
namespace Client
{
	public partial class ChannelPage
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView txtRoom;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Client.ChannelPage
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Client.ChannelPage";
			// Container child Client.ChannelPage.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtRoom = new global::Gtk.TextView();
			this.txtRoom.CanFocus = true;
			this.txtRoom.Name = "txtRoom";
			this.GtkScrolledWindow.Add(this.txtRoom);
			this.hbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
			w2.Position = 0;
			w2.Padding = ((uint)(10));
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
