
// This file has been generated by the GUI designer. Do not modify.
namespace Client
{
	public partial class FrmMain
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.ScrolledWindow scrollView;

		private global::Gtk.TextView txtRoom;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label lblUserName;

		private global::Gtk.Entry txtMessage;

		private global::Gtk.Button btSendMessage;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Client.FrmMain
			this.Name = "Client.FrmMain";
			this.Title = global::Mono.Unix.Catalog.GetString("Chat Client");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Client.FrmMain.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(10));
			this.alignment2.TopPadding = ((uint)(10));
			this.alignment2.RightPadding = ((uint)(10));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.scrollView = new global::Gtk.ScrolledWindow();
			this.scrollView.Name = "scrollView";
			this.scrollView.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrollView.Gtk.Container+ContainerChild
			this.txtRoom = new global::Gtk.TextView();
			this.txtRoom.CanFocus = true;
			this.txtRoom.Name = "txtRoom";
			this.scrollView.Add(this.txtRoom);
			this.alignment2.Add(this.scrollView);
			this.vbox1.Add(this.alignment2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment2]));
			w3.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblUserName = new global::Gtk.Label();
			this.lblUserName.Name = "lblUserName";
			this.lblUserName.LabelProp = global::Mono.Unix.Catalog.GetString("Usuário:");
			this.hbox1.Add(this.lblUserName);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblUserName]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtMessage = new global::Gtk.Entry();
			this.txtMessage.CanFocus = true;
			this.txtMessage.Name = "txtMessage";
			this.txtMessage.IsEditable = true;
			this.txtMessage.InvisibleChar = '•';
			this.hbox1.Add(this.txtMessage);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.txtMessage]));
			w5.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btSendMessage = new global::Gtk.Button();
			this.btSendMessage.CanFocus = true;
			this.btSendMessage.Name = "btSendMessage";
			this.btSendMessage.UseUnderline = true;
			this.btSendMessage.Label = global::Mono.Unix.Catalog.GetString("Enviar");
			this.hbox1.Add(this.btSendMessage);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btSendMessage]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w7.Position = 1;
			w7.Expand = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 406;
			this.DefaultHeight = 300;
			this.Show();
			this.txtMessage.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.OnTxtMessageKeyReleaseEvent);
			this.btSendMessage.Clicked += new global::System.EventHandler(this.OnBtSendMessageClicked);
		}
	}
}
