
// This file has been generated by the GUI designer. Do not modify.
namespace Client
{
	public partial class FrmMain
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HPaned hpaned1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView txtRoom;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeview1;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label lblUserName;

		private global::Gtk.Entry txtMessage;

		private global::Gtk.Button btSendMessage;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.HButtonBox channelsBox;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HSeparator hseparator6;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.HBox hbox3;

		private global::Client.Preloader imgLoading;

		private global::Gtk.Label lblStatus;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Client.FrmMain
			this.Name = "Client.FrmMain";
			this.Title = global::Mono.Unix.Catalog.GetString("Chat Client");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Client.FrmMain.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 350;
			this.hpaned1.BorderWidth = ((uint)(10));
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtRoom = new global::Gtk.TextView();
			this.txtRoom.CanFocus = true;
			this.txtRoom.Name = "txtRoom";
			this.GtkScrolledWindow.Add(this.txtRoom);
			this.hpaned1.Add(this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.GtkScrolledWindow]));
			w2.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow1.Add(this.treeview1);
			this.hpaned1.Add(this.GtkScrolledWindow1);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.GtkScrolledWindow1]));
			w4.Resize = false;
			this.vbox1.Add(this.hpaned1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hpaned1]));
			w5.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(10));
			this.alignment2.RightPadding = ((uint)(10));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblUserName = new global::Gtk.Label();
			this.lblUserName.Name = "lblUserName";
			this.lblUserName.LabelProp = global::Mono.Unix.Catalog.GetString("Usuário:");
			this.hbox1.Add(this.lblUserName);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblUserName]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtMessage = new global::Gtk.Entry();
			this.txtMessage.CanFocus = true;
			this.txtMessage.Name = "txtMessage";
			this.txtMessage.IsEditable = true;
			this.txtMessage.InvisibleChar = '•';
			this.hbox1.Add(this.txtMessage);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.txtMessage]));
			w7.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btSendMessage = new global::Gtk.Button();
			this.btSendMessage.CanFocus = true;
			this.btSendMessage.Name = "btSendMessage";
			this.btSendMessage.UseUnderline = true;
			this.btSendMessage.Label = global::Mono.Unix.Catalog.GetString("Enviar");
			this.hbox1.Add(this.btSendMessage);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btSendMessage]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.alignment2.Add(this.hbox1);
			this.vbox1.Add(this.alignment2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.vbox1.Add(this.hseparator2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator2]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(10));
			this.alignment1.RightPadding = ((uint)(10));
			this.alignment1.BottomPadding = ((uint)(10));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.channelsBox = new global::Gtk.HButtonBox();
			this.channelsBox.Name = "channelsBox";
			this.channelsBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			this.alignment1.Add(this.channelsBox);
			this.vbox1.Add(this.alignment1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment1]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator();
			this.hseparator6.Name = "hseparator6";
			this.vbox2.Add(this.hseparator6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator6]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.alignment4.LeftPadding = ((uint)(5));
			this.alignment4.TopPadding = ((uint)(2));
			this.alignment4.BottomPadding = ((uint)(2));
			// Container child alignment4.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.imgLoading = new global::Client.Preloader();
			this.imgLoading.Events = ((global::Gdk.EventMask)(256));
			this.imgLoading.Name = "imgLoading";
			this.hbox3.Add(this.imgLoading);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.imgLoading]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblStatus = new global::Gtk.Label();
			this.lblStatus.Name = "lblStatus";
			this.lblStatus.LabelProp = global::Mono.Unix.Catalog.GetString("Status...");
			this.hbox3.Add(this.lblStatus);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblStatus]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.alignment4.Add(this.hbox3);
			this.vbox2.Add(this.alignment4);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment4]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 494;
			this.DefaultHeight = 320;
			this.Show();
			this.txtMessage.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.OnTxtMessageKeyReleaseEvent);
			this.btSendMessage.Clicked += new global::System.EventHandler(this.OnBtSendMessageClicked);
		}
	}
}
