
// This file has been generated by the GUI designer. Do not modify.
namespace Client
{
	public partial class Preloader
	{
		private global::Gtk.Image imgAnimation;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Client.Preloader
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Client.Preloader";
			// Container child Client.Preloader.Gtk.Container+ContainerChild
			this.imgAnimation = new global::Gtk.Image();
			this.imgAnimation.Name = "imgAnimation";
			this.imgAnimation.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-execute", global::Gtk.IconSize.Menu);
			this.Add(this.imgAnimation);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
