version: '3'
services:
  messaging:
    build: ./MessagingServer
    depends_on:
      - "naming"
  naming:
    build: ./NamingServer
    ports:
      - "7777:7777"
  auth:
    build: ./AuthServer
    depends_on:
      - "naming"
      - "mongo"
  mongo:
    image: "mongo"
