// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MessagingServer.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatMessageType int32

const (
	ChatMessageType_TEXT    ChatMessageType = 0
	ChatMessageType_CONTROL ChatMessageType = 1
)

var ChatMessageType_name = map[int32]string{
	0: "TEXT",
	1: "CONTROL",
}

var ChatMessageType_value = map[string]int32{
	"TEXT":    0,
	"CONTROL": 1,
}

func (x ChatMessageType) String() string {
	return proto.EnumName(ChatMessageType_name, int32(x))
}

func (ChatMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e08173c4f010cdc7, []int{0}
}

type ControlMessageType int32

const (
	ControlMessageType_JOINED  ControlMessageType = 0
	ControlMessageType_AWAY    ControlMessageType = 1
	ControlMessageType_NAWAY   ControlMessageType = 2
	ControlMessageType_QUITTED ControlMessageType = 3
)

var ControlMessageType_name = map[int32]string{
	0: "JOINED",
	1: "AWAY",
	2: "NAWAY",
	3: "QUITTED",
}

var ControlMessageType_value = map[string]int32{
	"JOINED":  0,
	"AWAY":    1,
	"NAWAY":   2,
	"QUITTED": 3,
}

func (x ControlMessageType) String() string {
	return proto.EnumName(ControlMessageType_name, int32(x))
}

func (ControlMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e08173c4f010cdc7, []int{1}
}

type ControlMessage struct {
	Type                 ControlMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=Chat.Grpc.ControlMessageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ControlMessage) Reset()         { *m = ControlMessage{} }
func (m *ControlMessage) String() string { return proto.CompactTextString(m) }
func (*ControlMessage) ProtoMessage()    {}
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e08173c4f010cdc7, []int{0}
}

func (m *ControlMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlMessage.Unmarshal(m, b)
}
func (m *ControlMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlMessage.Marshal(b, m, deterministic)
}
func (m *ControlMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlMessage.Merge(m, src)
}
func (m *ControlMessage) XXX_Size() int {
	return xxx_messageInfo_ControlMessage.Size(m)
}
func (m *ControlMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ControlMessage proto.InternalMessageInfo

func (m *ControlMessage) GetType() ControlMessageType {
	if m != nil {
		return m.Type
	}
	return ControlMessageType_JOINED
}

type TextMessage struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextMessage) Reset()         { *m = TextMessage{} }
func (m *TextMessage) String() string { return proto.CompactTextString(m) }
func (*TextMessage) ProtoMessage()    {}
func (*TextMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e08173c4f010cdc7, []int{1}
}

func (m *TextMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextMessage.Unmarshal(m, b)
}
func (m *TextMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextMessage.Marshal(b, m, deterministic)
}
func (m *TextMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextMessage.Merge(m, src)
}
func (m *TextMessage) XXX_Size() int {
	return xxx_messageInfo_TextMessage.Size(m)
}
func (m *TextMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TextMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TextMessage proto.InternalMessageInfo

func (m *TextMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ChatMessage struct {
	Type           ChatMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=Chat.Grpc.ChatMessageType" json:"type,omitempty"`
	UserCredential *UserCredential `protobuf:"bytes,2,opt,name=user_credential,json=userCredential,proto3" json:"user_credential,omitempty"`
	DateTime       uint32          `protobuf:"varint,3,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Signature      []byte          `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*ChatMessage_Text
	//	*ChatMessage_Control
	Payload              isChatMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e08173c4f010cdc7, []int{2}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetType() ChatMessageType {
	if m != nil {
		return m.Type
	}
	return ChatMessageType_TEXT
}

func (m *ChatMessage) GetUserCredential() *UserCredential {
	if m != nil {
		return m.UserCredential
	}
	return nil
}

func (m *ChatMessage) GetDateTime() uint32 {
	if m != nil {
		return m.DateTime
	}
	return 0
}

func (m *ChatMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type isChatMessage_Payload interface {
	isChatMessage_Payload()
}

type ChatMessage_Text struct {
	Text *TextMessage `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type ChatMessage_Control struct {
	Control *ControlMessage `protobuf:"bytes,5,opt,name=control,proto3,oneof"`
}

func (*ChatMessage_Text) isChatMessage_Payload() {}

func (*ChatMessage_Control) isChatMessage_Payload() {}

func (m *ChatMessage) GetPayload() isChatMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ChatMessage) GetText() *TextMessage {
	if x, ok := m.GetPayload().(*ChatMessage_Text); ok {
		return x.Text
	}
	return nil
}

func (m *ChatMessage) GetControl() *ControlMessage {
	if x, ok := m.GetPayload().(*ChatMessage_Control); ok {
		return x.Control
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ChatMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ChatMessage_OneofMarshaler, _ChatMessage_OneofUnmarshaler, _ChatMessage_OneofSizer, []interface{}{
		(*ChatMessage_Text)(nil),
		(*ChatMessage_Control)(nil),
	}
}

func _ChatMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ChatMessage)
	// payload
	switch x := m.Payload.(type) {
	case *ChatMessage_Text:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Text); err != nil {
			return err
		}
	case *ChatMessage_Control:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Control); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ChatMessage.Payload has unexpected type %T", x)
	}
	return nil
}

func _ChatMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ChatMessage)
	switch tag {
	case 4: // payload.text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TextMessage)
		err := b.DecodeMessage(msg)
		m.Payload = &ChatMessage_Text{msg}
		return true, err
	case 5: // payload.control
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ControlMessage)
		err := b.DecodeMessage(msg)
		m.Payload = &ChatMessage_Control{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ChatMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ChatMessage)
	// payload
	switch x := m.Payload.(type) {
	case *ChatMessage_Text:
		s := proto.Size(x.Text)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ChatMessage_Control:
		s := proto.Size(x.Control)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterEnum("Chat.Grpc.ChatMessageType", ChatMessageType_name, ChatMessageType_value)
	proto.RegisterEnum("Chat.Grpc.ControlMessageType", ControlMessageType_name, ControlMessageType_value)
	proto.RegisterType((*ControlMessage)(nil), "Chat.Grpc.ControlMessage")
	proto.RegisterType((*TextMessage)(nil), "Chat.Grpc.TextMessage")
	proto.RegisterType((*ChatMessage)(nil), "Chat.Grpc.ChatMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessagingServerClient is the client API for MessagingServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessagingServerClient interface {
	TalkAndListen(ctx context.Context, opts ...grpc.CallOption) (MessagingServer_TalkAndListenClient, error)
}

type messagingServerClient struct {
	cc *grpc.ClientConn
}

func NewMessagingServerClient(cc *grpc.ClientConn) MessagingServerClient {
	return &messagingServerClient{cc}
}

func (c *messagingServerClient) TalkAndListen(ctx context.Context, opts ...grpc.CallOption) (MessagingServer_TalkAndListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MessagingServer_serviceDesc.Streams[0], "/Chat.Grpc.MessagingServer/TalkAndListen", opts...)
	if err != nil {
		return nil, err
	}
	x := &messagingServerTalkAndListenClient{stream}
	return x, nil
}

type MessagingServer_TalkAndListenClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type messagingServerTalkAndListenClient struct {
	grpc.ClientStream
}

func (x *messagingServerTalkAndListenClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messagingServerTalkAndListenClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessagingServerServer is the server API for MessagingServer service.
type MessagingServerServer interface {
	TalkAndListen(MessagingServer_TalkAndListenServer) error
}

func RegisterMessagingServerServer(s *grpc.Server, srv MessagingServerServer) {
	s.RegisterService(&_MessagingServer_serviceDesc, srv)
}

func _MessagingServer_TalkAndListen_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessagingServerServer).TalkAndListen(&messagingServerTalkAndListenServer{stream})
}

type MessagingServer_TalkAndListenServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type messagingServerTalkAndListenServer struct {
	grpc.ServerStream
}

func (x *messagingServerTalkAndListenServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messagingServerTalkAndListenServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MessagingServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Chat.Grpc.MessagingServer",
	HandlerType: (*MessagingServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TalkAndListen",
			Handler:       _MessagingServer_TalkAndListen_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "MessagingServer.proto",
}

func init() { proto.RegisterFile("MessagingServer.proto", fileDescriptor_e08173c4f010cdc7) }

var fileDescriptor_e08173c4f010cdc7 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xef, 0x6e, 0x93, 0x50,
	0x14, 0xe7, 0x76, 0xac, 0x1d, 0x07, 0xd7, 0x92, 0x9b, 0xb8, 0x60, 0xd5, 0x04, 0xf9, 0x44, 0x16,
	0x43, 0xb4, 0xc6, 0x07, 0x00, 0x46, 0xdc, 0xcc, 0x6c, 0x23, 0xde, 0xc5, 0xe9, 0x97, 0xe5, 0x0a,
	0x27, 0x8c, 0xc8, 0x80, 0x5c, 0x2e, 0x66, 0x7d, 0x27, 0x1f, 0xd2, 0x40, 0xed, 0x0a, 0xab, 0x7e,
	0x3b, 0x1c, 0x7e, 0x7f, 0xee, 0xf9, 0x9d, 0x03, 0x4f, 0x3f, 0x61, 0x5d, 0xf3, 0x34, 0x2b, 0xd2,
	0x2f, 0x28, 0x7e, 0xa1, 0x70, 0x2b, 0x51, 0xca, 0x92, 0x6a, 0xc1, 0x2d, 0x97, 0xee, 0x07, 0x51,
	0xc5, 0x73, 0xc3, 0x6b, 0xe4, 0x6d, 0xff, 0xa7, 0x1d, 0xc0, 0x34, 0x28, 0x0b, 0x29, 0xca, 0x7c,
	0x43, 0x46, 0xfa, 0x16, 0x54, 0xb9, 0xae, 0xd0, 0x24, 0x16, 0x71, 0xa6, 0x8b, 0x97, 0xee, 0x03,
	0xdb, 0x1d, 0x02, 0xd9, 0xba, 0xc2, 0xa8, 0x83, 0xda, 0xaf, 0x40, 0x67, 0x78, 0x2f, 0xb7, 0x0a,
	0x14, 0x54, 0x89, 0xf7, 0xb2, 0x53, 0xd0, 0xa2, 0xae, 0xb6, 0x7f, 0x8f, 0x40, 0x6f, 0x95, 0xb6,
	0x18, 0x77, 0xe0, 0x32, 0xef, 0xbb, 0xec, 0x50, 0x3b, 0x0b, 0xea, 0xc3, 0xac, 0xa9, 0x51, 0xdc,
	0xc4, 0x02, 0x13, 0x2c, 0x64, 0xc6, 0x73, 0x73, 0x64, 0x11, 0x47, 0x5f, 0x3c, 0xeb, 0x51, 0xaf,
	0x6a, 0x14, 0xc1, 0x03, 0x20, 0x9a, 0x36, 0x83, 0x6f, 0xfa, 0x1c, 0xb4, 0x84, 0x4b, 0xbc, 0x91,
	0xd9, 0x1d, 0x9a, 0x07, 0x16, 0x71, 0x8e, 0xa3, 0xa3, 0xb6, 0xc1, 0xb2, 0x3b, 0xa4, 0x2f, 0x40,
	0xab, 0xb3, 0xb4, 0xe0, 0xb2, 0x11, 0x68, 0x8e, 0x2d, 0xe2, 0x3c, 0x89, 0x76, 0x0d, 0xfa, 0xfa,
	0xef, 0x48, 0x6a, 0xe7, 0x79, 0xd2, 0xf3, 0xec, 0x0d, 0x7e, 0xae, 0x6c, 0x86, 0xa5, 0xef, 0x61,
	0x12, 0x6f, 0xb2, 0x32, 0x0f, 0xf7, 0x1e, 0x39, 0x4c, 0xf1, 0x5c, 0x89, 0xb6, 0x58, 0x5f, 0x83,
	0x49, 0xc5, 0xd7, 0x79, 0xc9, 0x93, 0x53, 0x07, 0x66, 0x8f, 0x72, 0xa0, 0x47, 0xa0, 0xb2, 0xf0,
	0x9a, 0x19, 0x0a, 0xd5, 0x61, 0x12, 0xac, 0x96, 0x2c, 0x5a, 0x5d, 0x1a, 0xe4, 0xd4, 0x07, 0xba,
	0xbf, 0x17, 0x0a, 0x30, 0xfe, 0xb8, 0xba, 0x58, 0x86, 0x67, 0x86, 0xd2, 0x12, 0xbd, 0xaf, 0xde,
	0x37, 0x83, 0x50, 0x0d, 0x0e, 0x97, 0x5d, 0x39, 0x6a, 0x35, 0x3e, 0x5f, 0x5d, 0x30, 0x16, 0x9e,
	0x19, 0x07, 0x8b, 0x6b, 0x98, 0x3d, 0x3a, 0x1d, 0x1a, 0xc2, 0x31, 0xe3, 0xf9, 0x4f, 0xaf, 0x48,
	0x2e, 0xb3, 0x5a, 0x62, 0x41, 0x4f, 0xfe, 0xbd, 0xa2, 0xf9, 0x7f, 0xfa, 0xb6, 0xe2, 0x90, 0x37,
	0xc4, 0x1f, 0x7f, 0x57, 0x53, 0x51, 0xc5, 0x3f, 0xc6, 0xdd, 0xb5, 0xbd, 0xfb, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x26, 0xa6, 0x1e, 0xd9, 0xa3, 0x02, 0x00, 0x00,
}
