// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessagingServer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chat.Grpc {

  /// <summary>Holder for reflection information generated from MessagingServer.proto</summary>
  public static partial class MessagingServerReflection {

    #region Descriptor
    /// <summary>File descriptor for MessagingServer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagingServerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVNZXNzYWdpbmdTZXJ2ZXIucHJvdG8SCUNoYXQuR3JwYxoQQXV0aFNlcnZl",
            "ci5wcm90byIbCgtUZXh0TWVzc2FnZRIMCgR0ZXh0GAEgASgJIs0BCgtDaGF0",
            "TWVzc2FnZRI0CgR0eXBlGAEgASgOMiYuQ2hhdC5HcnBjLkNoYXRNZXNzYWdl",
            "LkNoYXRNZXNzYWdlVHlwZRIyCg91c2VyX2NyZWRlbnRpYWwYAiABKAsyGS5D",
            "aGF0LkdycGMuVXNlckNyZWRlbnRpYWwSEQoJZGF0ZV90aW1lGAMgASgNEiQK",
            "BHRleHQYBCABKAsyFi5DaGF0LkdycGMuVGV4dE1lc3NhZ2UiGwoPQ2hhdE1l",
            "c3NhZ2VUeXBlEggKBFRFWFQQADJYCg9NZXNzYWdpbmdTZXJ2ZXISRQoNVGFs",
            "a0FuZExpc3RlbhIWLkNoYXQuR3JwYy5DaGF0TWVzc2FnZRoWLkNoYXQuR3Jw",
            "Yy5DaGF0TWVzc2FnZSIAKAEwAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Chat.Grpc.AuthServerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Grpc.TextMessage), global::Chat.Grpc.TextMessage.Parser, new[]{ "Text" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Grpc.ChatMessage), global::Chat.Grpc.ChatMessage.Parser, new[]{ "Type", "UserCredential", "DateTime", "Text" }, null, new[]{ typeof(global::Chat.Grpc.ChatMessage.Types.ChatMessageType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TextMessage : pb::IMessage<TextMessage> {
    private static readonly pb::MessageParser<TextMessage> _parser = new pb::MessageParser<TextMessage>(() => new TextMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TextMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.Grpc.MessagingServerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TextMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TextMessage(TextMessage other) : this() {
      text_ = other.text_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TextMessage Clone() {
      return new TextMessage(this);
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 1;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TextMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TextMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Text != other.Text) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TextMessage other) {
      if (other == null) {
        return;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ChatMessage : pb::IMessage<ChatMessage> {
    private static readonly pb::MessageParser<ChatMessage> _parser = new pb::MessageParser<ChatMessage>(() => new ChatMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChatMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.Grpc.MessagingServerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatMessage(ChatMessage other) : this() {
      type_ = other.type_;
      userCredential_ = other.userCredential_ != null ? other.userCredential_.Clone() : null;
      dateTime_ = other.dateTime_;
      text_ = other.text_ != null ? other.text_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatMessage Clone() {
      return new ChatMessage(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Chat.Grpc.ChatMessage.Types.ChatMessageType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Chat.Grpc.ChatMessage.Types.ChatMessageType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "user_credential" field.</summary>
    public const int UserCredentialFieldNumber = 2;
    private global::Chat.Grpc.UserCredential userCredential_;
    /// <summary>
    /// somente para envio
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Chat.Grpc.UserCredential UserCredential {
      get { return userCredential_; }
      set {
        userCredential_ = value;
      }
    }

    /// <summary>Field number for the "date_time" field.</summary>
    public const int DateTimeFieldNumber = 3;
    private uint dateTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DateTime {
      get { return dateTime_; }
      set {
        dateTime_ = value;
      }
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 4;
    private global::Chat.Grpc.TextMessage text_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Chat.Grpc.TextMessage Text {
      get { return text_; }
      set {
        text_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChatMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChatMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(UserCredential, other.UserCredential)) return false;
      if (DateTime != other.DateTime) return false;
      if (!object.Equals(Text, other.Text)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (userCredential_ != null) hash ^= UserCredential.GetHashCode();
      if (DateTime != 0) hash ^= DateTime.GetHashCode();
      if (text_ != null) hash ^= Text.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (userCredential_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserCredential);
      }
      if (DateTime != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(DateTime);
      }
      if (text_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (userCredential_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserCredential);
      }
      if (DateTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DateTime);
      }
      if (text_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Text);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChatMessage other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.userCredential_ != null) {
        if (userCredential_ == null) {
          userCredential_ = new global::Chat.Grpc.UserCredential();
        }
        UserCredential.MergeFrom(other.UserCredential);
      }
      if (other.DateTime != 0) {
        DateTime = other.DateTime;
      }
      if (other.text_ != null) {
        if (text_ == null) {
          text_ = new global::Chat.Grpc.TextMessage();
        }
        Text.MergeFrom(other.Text);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            type_ = (global::Chat.Grpc.ChatMessage.Types.ChatMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (userCredential_ == null) {
              userCredential_ = new global::Chat.Grpc.UserCredential();
            }
            input.ReadMessage(userCredential_);
            break;
          }
          case 24: {
            DateTime = input.ReadUInt32();
            break;
          }
          case 34: {
            if (text_ == null) {
              text_ = new global::Chat.Grpc.TextMessage();
            }
            input.ReadMessage(text_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ChatMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ChatMessageType {
        [pbr::OriginalName("TEXT")] Text = 0,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
