// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessagingServer.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Chat.Grpc {
  public static partial class MessagingServer
  {
    static readonly string __ServiceName = "Chat.Grpc.MessagingServer";

    static readonly grpc::Marshaller<global::Chat.Grpc.ChatMessage> __Marshaller_Chat_Grpc_ChatMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Chat.Grpc.ChatMessage.Parser.ParseFrom);

    static readonly grpc::Method<global::Chat.Grpc.ChatMessage, global::Chat.Grpc.ChatMessage> __Method_TalkAndListen = new grpc::Method<global::Chat.Grpc.ChatMessage, global::Chat.Grpc.ChatMessage>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "TalkAndListen",
        __Marshaller_Chat_Grpc_ChatMessage,
        __Marshaller_Chat_Grpc_ChatMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Chat.Grpc.MessagingServerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MessagingServer</summary>
    public abstract partial class MessagingServerBase
    {
      public virtual global::System.Threading.Tasks.Task TalkAndListen(grpc::IAsyncStreamReader<global::Chat.Grpc.ChatMessage> requestStream, grpc::IServerStreamWriter<global::Chat.Grpc.ChatMessage> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MessagingServer</summary>
    public partial class MessagingServerClient : grpc::ClientBase<MessagingServerClient>
    {
      /// <summary>Creates a new client for MessagingServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MessagingServerClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MessagingServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MessagingServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MessagingServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MessagingServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Chat.Grpc.ChatMessage, global::Chat.Grpc.ChatMessage> TalkAndListen(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TalkAndListen(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Chat.Grpc.ChatMessage, global::Chat.Grpc.ChatMessage> TalkAndListen(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_TalkAndListen, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MessagingServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MessagingServerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MessagingServerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_TalkAndListen, serviceImpl.TalkAndListen).Build();
    }

  }
}
#endregion
